# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AutopusMcpServer < Formula
  desc "Autopus MCP Server - Claude Code MCP plugin for Autopus platform integration"
  homepage "https://github.com/insajin/autopus-bridge"
  version "1.13.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Insajin/autopus-bridge/releases/download/v1.13.0/autopus-mcp-server_1.13.0_darwin_amd64.tar.gz"
      sha256 "f9d8ccd0139c6876cdd4f40cd7ea27ef0a8f60c2067ed62e22edad4a05d2e16e"

      define_method(:install) do
        bin.install "autopus-mcp-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Insajin/autopus-bridge/releases/download/v1.13.0/autopus-mcp-server_1.13.0_darwin_arm64.tar.gz"
      sha256 "bf7b3fe6e725124ae65ffbb8c82d5f681107db9ebe38d156cba2e67fd27864dd"

      define_method(:install) do
        bin.install "autopus-mcp-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Insajin/autopus-bridge/releases/download/v1.13.0/autopus-mcp-server_1.13.0_linux_amd64.tar.gz"
      sha256 "72b4d00b6bee5088f1acbd5abcf71d25a4f370e3f06f1cd28309ec63ed231fc8"
      define_method(:install) do
        bin.install "autopus-mcp-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Insajin/autopus-bridge/releases/download/v1.13.0/autopus-mcp-server_1.13.0_linux_arm64.tar.gz"
      sha256 "289b1d229a0603b48dcf2f6249ebff5276f6a05e82bb6fceb7eb6ad16c6ebd37"
      define_method(:install) do
        bin.install "autopus-mcp-server"
      end
    end
  end

  test do
    assert_predicate bin/"autopus-mcp-server", :exist?
  end
end
