# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AutopusMcpServer < Formula
  desc "Autopus MCP Server - Claude Code MCP plugin for Autopus platform integration"
  homepage "https://github.com/insajin/autopus-bridge"
  version "1.14.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Insajin/autopus-bridge/releases/download/v1.14.1/autopus-mcp-server_1.14.1_darwin_amd64.tar.gz"
      sha256 "12311f9f33182c96f0871368483f04c14425744ec27178cf1afe2162104500ff"

      define_method(:install) do
        bin.install "autopus-mcp-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Insajin/autopus-bridge/releases/download/v1.14.1/autopus-mcp-server_1.14.1_darwin_arm64.tar.gz"
      sha256 "7880fe6a9a2494d3bda1d49bd10169619af510e99b658021e17dce15c5c4e4c0"

      define_method(:install) do
        bin.install "autopus-mcp-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Insajin/autopus-bridge/releases/download/v1.14.1/autopus-mcp-server_1.14.1_linux_amd64.tar.gz"
      sha256 "9c026e4b74ea1a6ecd88db948863f7991455b5008e3fee0f2bc3d993ede7b553"
      define_method(:install) do
        bin.install "autopus-mcp-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Insajin/autopus-bridge/releases/download/v1.14.1/autopus-mcp-server_1.14.1_linux_arm64.tar.gz"
      sha256 "50104f12a1402025d46525cfe2d3dbf495b1e662c9bfc6fac2fe69035d479728"
      define_method(:install) do
        bin.install "autopus-mcp-server"
      end
    end
  end

  test do
    assert_predicate bin/"autopus-mcp-server", :exist?
  end
end
