# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AutopusBridge < Formula
  desc "Autopus Local Agent Bridge - Connect local development agents to Autopus platform"
  homepage "https://github.com/insajin/autopus-bridge"
  version "1.15.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Insajin/autopus-bridge/releases/download/v1.15.0/autopus-bridge_1.15.0_darwin_amd64.tar.gz"
      sha256 "0d630e28c20005b1acc57ab3338e8ab64bd812f0069e0d8c714f49107c5183a6"

      define_method(:install) do
        bin.install "autopus-bridge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Insajin/autopus-bridge/releases/download/v1.15.0/autopus-bridge_1.15.0_darwin_arm64.tar.gz"
      sha256 "85139b2f0fe06aa9a959df048feb0e2a1297abd14c12eca3cd85cc4311cad8ba"

      define_method(:install) do
        bin.install "autopus-bridge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Insajin/autopus-bridge/releases/download/v1.15.0/autopus-bridge_1.15.0_linux_amd64.tar.gz"
      sha256 "ac828b471bf1e2256051069588de4fd8d03b01d8b349d57337cd1848b6ac1a48"
      define_method(:install) do
        bin.install "autopus-bridge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Insajin/autopus-bridge/releases/download/v1.15.0/autopus-bridge_1.15.0_linux_arm64.tar.gz"
      sha256 "a342814e8c0d83dc49ed12d5186b192ee397e4487f8f3ba38a2c903cb44026eb"
      define_method(:install) do
        bin.install "autopus-bridge"
      end
    end
  end

  test do
    system "#{bin}/autopus-bridge", "version"
  end
end
