# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AutopusMcpServer < Formula
  desc "Autopus MCP Server - Claude Code MCP plugin for Autopus platform integration"
  homepage "https://github.com/insajin/autopus-bridge"
  version "1.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Insajin/autopus-bridge/releases/download/v1.6.0/autopus-mcp-server_1.6.0_darwin_amd64.tar.gz"
      sha256 "c48450e76d4206c0a91dc898fe713ee2b9670e5547cd59adb4e43528f4ba84f5"

      define_method(:install) do
        bin.install "autopus-mcp-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Insajin/autopus-bridge/releases/download/v1.6.0/autopus-mcp-server_1.6.0_darwin_arm64.tar.gz"
      sha256 "cc04af345323e8299d071438b747e5ce709ff5f71628b53ec2f7082767f41497"

      define_method(:install) do
        bin.install "autopus-mcp-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Insajin/autopus-bridge/releases/download/v1.6.0/autopus-mcp-server_1.6.0_linux_amd64.tar.gz"
      sha256 "a1edc9df4f856623c64b9297c02dfad98ce967ba9a1ab7a7b94a22cf645351e0"
      define_method(:install) do
        bin.install "autopus-mcp-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Insajin/autopus-bridge/releases/download/v1.6.0/autopus-mcp-server_1.6.0_linux_arm64.tar.gz"
      sha256 "c82064cbb9e0b7408ba674493370a162b7923a41e219152413e65e35974c78bf"
      define_method(:install) do
        bin.install "autopus-mcp-server"
      end
    end
  end

  test do
    assert_predicate bin/"autopus-mcp-server", :exist?
  end
end
