# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AutopusBridge < Formula
  desc "Autopus Local Agent Bridge - Connect local development agents to Autopus platform"
  homepage "https://github.com/insajin/autopus-bridge"
  version "1.22.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Insajin/autopus-bridge/releases/download/v1.22.1/autopus-bridge_1.22.1_darwin_amd64.tar.gz"
      sha256 "0e8ad4342767293614bbeaea32d748c1306ae4a0594b8d7b1474fdb2b64f6f8d"

      define_method(:install) do
        bin.install "autopus-bridge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Insajin/autopus-bridge/releases/download/v1.22.1/autopus-bridge_1.22.1_darwin_arm64.tar.gz"
      sha256 "dc524572eecb1ebf606c289176765d4202168a59993947a4d6ba12479564a66d"

      define_method(:install) do
        bin.install "autopus-bridge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Insajin/autopus-bridge/releases/download/v1.22.1/autopus-bridge_1.22.1_linux_amd64.tar.gz"
      sha256 "f2be0234956d57d63441fea8a2b17f69ff64d2631166dde8a24578cd50ddecb8"
      define_method(:install) do
        bin.install "autopus-bridge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Insajin/autopus-bridge/releases/download/v1.22.1/autopus-bridge_1.22.1_linux_arm64.tar.gz"
      sha256 "7d8b174466b52e5be50cf9209cd9d75eb5ab39f4f714b1d5f4e5725ab0c389f0"
      define_method(:install) do
        bin.install "autopus-bridge"
      end
    end
  end

  test do
    system "#{bin}/autopus-bridge", "version"
  end
end
