# This file was generated by GoReleaser. DO NOT EDIT.
cask "autopus-bridge" do
  name "autopus-bridge"
  desc "Autopus Local Agent Bridge - Connect local development agents to Autopus platform"
  homepage "https://github.com/insajin/autopus-bridge"
  version "1.35.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "autopus-bridge"

  on_macos do
    on_intel do
      url "https://github.com/Insajin/autopus-bridge/releases/download/v#{version}/autopus-bridge_#{version}_darwin_amd64.tar.gz"
      sha256 "29ef8becbcaf1c7dbd3dca33d7a3b81d80bada037399d1ff10e3ffe04646ca70"
    end
    on_arm do
      url "https://github.com/Insajin/autopus-bridge/releases/download/v#{version}/autopus-bridge_#{version}_darwin_arm64.tar.gz"
      sha256 "f9fb60aa10f8ecaa7ee0b0cae090a96c3208634f98c39521ebf98a72ca5c2e02"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Insajin/autopus-bridge/releases/download/v#{version}/autopus-bridge_#{version}_linux_amd64.tar.gz"
      sha256 "2840fe3df6166e4c0f9a179b45c8d8cbfc0589e88ad6ceb38afb74e78f7a1007"
    end
    on_arm do
      url "https://github.com/Insajin/autopus-bridge/releases/download/v#{version}/autopus-bridge_#{version}_linux_arm64.tar.gz"
      sha256 "5a5a0c0f312cdaafbe67093702747dc3ba96885b2f92942785f954a99c54950d"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/autopus-bridge"]
    end
  end

  # No zap stanza required
end
