# This file was generated by GoReleaser. DO NOT EDIT.
cask "autopus-mcp-server" do
  name "autopus-mcp-server"
  desc "Autopus MCP Server - Claude Code MCP plugin for Autopus platform integration"
  homepage "https://github.com/insajin/autopus-bridge"
  version "1.24.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "autopus-mcp-server"

  on_macos do
    on_intel do
      url "https://github.com/Insajin/autopus-bridge/releases/download/v#{version}/autopus-mcp-server_#{version}_darwin_amd64.tar.gz"
      sha256 "bcf25d47bac59018a1a068aa33c23227949a25a87ee508dfb857c4ff6bed0a2f"
    end
    on_arm do
      url "https://github.com/Insajin/autopus-bridge/releases/download/v#{version}/autopus-mcp-server_#{version}_darwin_arm64.tar.gz"
      sha256 "763d760a3f9176b1fb0af217d32cc783c2b1d79cb62562cc46fa2fce5112ec42"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Insajin/autopus-bridge/releases/download/v#{version}/autopus-mcp-server_#{version}_linux_amd64.tar.gz"
      sha256 "568d2f9936f1d83f6649e70696e590efa0ab4af11c5ef904abbb5f8edb0615c5"
    end
    on_arm do
      url "https://github.com/Insajin/autopus-bridge/releases/download/v#{version}/autopus-mcp-server_#{version}_linux_arm64.tar.gz"
      sha256 "30cd75d5c93c41ae09f09e21765180d3be84fa9b73ac681d6ce65ce1d3175227"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/autopus-mcp-server"]
    end
  end

  # No zap stanza required
end
