# This file was generated by GoReleaser. DO NOT EDIT.
cask "autopus-bridge" do
  name "autopus-bridge"
  desc "Autopus Local Agent Bridge - Connect local development agents to Autopus platform"
  homepage "https://github.com/insajin/autopus-bridge"
  version "1.27.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "autopus-bridge"

  on_macos do
    on_intel do
      url "https://github.com/Insajin/autopus-bridge/releases/download/v#{version}/autopus-bridge_#{version}_darwin_amd64.tar.gz"
      sha256 "ba923591367a2b1f2c138761c6820aa50ece5ee6f0eb120b2d4a7f0c77efcf84"
    end
    on_arm do
      url "https://github.com/Insajin/autopus-bridge/releases/download/v#{version}/autopus-bridge_#{version}_darwin_arm64.tar.gz"
      sha256 "962118a0e5ebb10be9fe5406a408610a3deab3bd9515deb1f503276d1bf81017"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Insajin/autopus-bridge/releases/download/v#{version}/autopus-bridge_#{version}_linux_amd64.tar.gz"
      sha256 "1d5645524453b1b7cb92fb95693e8a8fcc6cdb3516d244fb096ff26577ee0cdd"
    end
    on_arm do
      url "https://github.com/Insajin/autopus-bridge/releases/download/v#{version}/autopus-bridge_#{version}_linux_arm64.tar.gz"
      sha256 "7eb967e805f4c7306a2fcc128de27e8b9428523796cee20d96085e4b6b932b0d"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/autopus-bridge"]
    end
  end

  # No zap stanza required
end
