# This file was generated by GoReleaser. DO NOT EDIT.
cask "autopus-bridge" do
  name "autopus-bridge"
  desc "Autopus Local Agent Bridge - Connect local development agents to Autopus platform"
  homepage "https://github.com/insajin/autopus-bridge"
  version "1.27.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "autopus-bridge"

  on_macos do
    on_intel do
      url "https://github.com/Insajin/autopus-bridge/releases/download/v#{version}/autopus-bridge_#{version}_darwin_amd64.tar.gz"
      sha256 "1cf3dfaaa6e17828c04232dffdc87f2d37bed7ae88842ad0685ee1dd90e93b4f"
    end
    on_arm do
      url "https://github.com/Insajin/autopus-bridge/releases/download/v#{version}/autopus-bridge_#{version}_darwin_arm64.tar.gz"
      sha256 "a115634e2476d402f799b121e9ed5ded81f5d5c58d33eb568c75ac67b028f0af"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Insajin/autopus-bridge/releases/download/v#{version}/autopus-bridge_#{version}_linux_amd64.tar.gz"
      sha256 "a31d7ebd8a6a200fcf7a5b909796f60ce508bb4e9c561b58ed6e856b0f5fc15b"
    end
    on_arm do
      url "https://github.com/Insajin/autopus-bridge/releases/download/v#{version}/autopus-bridge_#{version}_linux_arm64.tar.gz"
      sha256 "0e3d3372ca9edd29d3b42da7d522092d99f985f90ffbb8e8372b2d0b21552a15"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/autopus-bridge"]
    end
  end

  # No zap stanza required
end
